# Generated by Django 3.1.5 on 2021-01-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_email', models.CharField(help_text='write your email', max_length=50, primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=30)),
                ('hospital_city', models.CharField(max_length=20)),
                ('hospital_mobile_no', models.CharField(max_length=10)),
                ('hospital_address', models.CharField(help_text='write your email', max_length=100)),
                ('zip_code', models.CharField(max_length=6)),
            ],
        ),
    ]
