# Generated by Django 3.1.5 on 2021-02-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=50)),
                ('donor_dob', models.DateTimeField()),
                ('donor_height', models.CharField(max_length=50)),
                ('donor_weight', models.CharField(max_length=50)),
                ('donor_bloodGroup', models.CharField(max_length=10)),
                ('donor_gender', models.CharField(max_length=10)),
                ('donor_diseases', models.CharField(blank=True, max_length=50)),
                ('donor_addiction', models.CharField(blank=True, max_length=50)),
                ('donor_info', models.CharField(blank=True, max_length=200)),
                ('donor_added_time', models.DateTimeField(default=None)),
            ],
        ),
    ]
