# Generated by Django 3.0.3 on 2021-02-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_donor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='assign_id',
            new_name='donor_id',
        ),
    ]
