# Generated by Django 3.0.3 on 2021-01-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20210125_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='photos/ereader.png', upload_to='photos/', verbose_name='Photo'),
        ),
    ]
