# Generated by Django 3.0.3 on 2021-02-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20210203_2243'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donor',
            unique_together={('donor_id', 'hospital_email')},
        ),
    ]
