# Generated by Django 3.1.5 on 2021-02-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20210203_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='hospital_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
