# Generated by Django 3.0.3 on 2021-02-16 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_remove_donor_hospital_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganRequest',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('organ_request_time', models.DateTimeField(auto_now_add=True)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='hospital.Hospital')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='hospital.Hospital')),
            ],
        ),
    ]
