# Generated by Django 3.1.5 on 2021-02-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_organrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='organrequest',
            name='donor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Donor', to='hospital.donor'),
        ),
    ]
