# Generated by Django 3.0.3 on 2021-02-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_organrequest_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organrequest',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
