# Generated by Django 3.0.3 on 2021-02-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_auto_20210217_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organrequest',
            old_name='status',
            new_name='accepted',
        ),
        migrations.AddField(
            model_name='organrequest',
            name='declined',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
