# Generated by Django 3.1.5 on 2021-02-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_auto_20210217_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='organrequest',
            name='pending',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
