# Generated by Django 3.0.3 on 2021-02-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_transplant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=50)),
                ('organ', models.CharField(max_length=30)),
            ],
        ),
    ]
