# Generated by Django 3.0.3 on 2021-02-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_donation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
