# Generated by Django 3.0.3 on 2021-02-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_delete_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=50)),
                ('organ', models.CharField(max_length=30)),
                ('details_added_time', models.DateTimeField(default=None)),
            ],
        ),
    ]
