# Generated by Django 3.0.3 on 2021-02-24 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_auto_20210224_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=50)),
                ('organ', models.CharField(max_length=30)),
                ('details_added_time', models.DateTimeField(default=None)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital')),
            ],
        ),
    ]
