# Generated by Django 3.1.5 on 2021-02-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoluntaryDonation',
            fields=[
                ('volunteer_email', models.CharField(help_text='write your email', max_length=50, primary_key=True, serialize=False)),
                ('volunteer_name', models.CharField(max_length=30)),
                ('volunteer_city', models.CharField(max_length=20)),
                ('volunteer_mobile_no', models.CharField(max_length=10)),
                ('volunteer_bloodGroup', models.CharField(max_length=10)),
            ],
        ),
    ]
