# Generated by Django 3.1.5 on 2021-02-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VoluntaryDonation',
            new_name='Volunteer',
        ),
    ]
