# Generated by Django 3.1.5 on 2021-02-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donation', '0002_auto_20210202_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteer_bloodGroup',
        ),
    ]
