# Generated by Django 3.1.5 on 2021-02-02 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donation', '0003_remove_volunteer_volunteer_bloodgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='volunteer_city',
            new_name='vol_city',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='volunteer_email',
            new_name='vol_email',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='volunteer_mobile_no',
            new_name='vol_mobile_no',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='volunteer_name',
            new_name='vol_name',
        ),
    ]
