# Generated by Django 3.1.5 on 2021-02-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donation', '0004_auto_20210202_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='vol_city',
            new_name='volunteer_city',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='vol_email',
            new_name='volunteer_email',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='vol_mobile_no',
            new_name='volunteer_mobile_no',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='vol_name',
            new_name='volunteer_name',
        ),
    ]
