# Generated by Django 3.1.5 on 2021-02-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donation', '0006_volunteer_volunteer_bloodgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_gender',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
