# Generated by Django 3.1.5 on 2021-02-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donation', '0007_volunteer_volunteer_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteer_gender',
        ),
    ]
